#!/usr/bin/env python3
"""Report the difference between BoltBeam kernel authority and ordinary NV selection."""
from __future__ import annotations

import argparse, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GENERATED = ROOT / "tinygrad/llm/generated"
LEDGER = GENERATED / "boltbeam-nv-sm120-kernel-authority.json"


def _sources(root: Path) -> dict[str, str]:
  return {str(path.relative_to(ROOT)):path.read_text(errors="replace")
          for path in root.rglob("*.py") if "__pycache__" not in path.parts}


def inventory() -> dict:
  authority = json.loads(LEDGER.read_text())
  production = _sources(ROOT / "tinygrad/llm")
  research = _sources(ROOT / "extra/llm_research")
  rows = []
  for route in authority["routes"]:
    policy_name = route.get("route_policy")
    policy = json.loads((GENERATED / policy_name).read_text()) if policy_name else None
    promoted = bool(policy and {"backend":"NV", "architecture":"sm_120"} in policy.get("promoted_targets", []))
    policy_readers = sorted(name for name, text in production.items() if policy_name and policy_name in text)
    production_refs = sorted(name for name, text in production.items() if route["route_id"] in text)
    research_refs = sorted(name for name, text in research.items() if route["route_id"] in text)
    if policy_name and not promoted: status = "closed_policy"
    elif policy_name and policy_readers and production_refs: status = "selected_binding_present"
    elif policy_name and policy_readers: status = "policy_binding_present"
    elif production_refs: status = "production_reference_only"
    else: status = "authority_only"
    rows.append({**route, "nv_sm120_promoted":promoted, "integration_status":status,
                 "policy_readers":policy_readers, "production_refs":production_refs,
                 "research_refs":research_refs})
  counts = {}
  for row in rows: counts[row["integration_status"]] = counts.get(row["integration_status"], 0) + 1
  return {"schema":"tinygrad.nv_generated_corpus_inventory.v1", "target":authority["target"],
          "counts":counts, "routes":rows,
          "notes":[
            "Authority state describes reproducibility, not ordinary runtime selection.",
            "A selected_binding_present row proves static policy and call-site reachability; runtime census remains the selection authority.",
            "generated/catalog.json belongs to the separate immutable artifact seam and is not used to infer route selection."
          ]}


def markdown(report: dict) -> str:
  lines = ["# NV generated corpus integration inventory", "", "Generated by `extra/audit/nv_generated_corpus_inventory.py`.", "",
           "Authority and ordinary selection are intentionally reported separately. Static reachability is an integration checkpoint; the live program census is the final authority.", "",
           "| phase | route | exact state | NV policy | static integration |", "| --- | --- | --- | --- | --- |"]
  for row in report["routes"]:
    policy = "promoted" if row["nv_sm120_promoted"] else ("closed" if row["route_policy"] else "none")
    lines.append(f"| {row['phase']} | `{row['route_id']}` | {row['state']} | {policy} | {row['integration_status']} |")
  lines += ["", "## Counts", ""]
  lines += [f"- `{key}`: {value}" for key,value in sorted(report["counts"].items())]
  lines += ["", "## Immediate integration conclusions", "",
            "- Prefill fused attention has exact authority, an NV-promoted policy, a production policy reader, and an authorized lowering call site.",
            "- Prefill Q6 stream-K down has exact authority and provider emitters, but no production reference. It is the clearest orphaned winning route.",
            "- Closed decode policies are reproducible corpus assets, but their empty target lists deliberately prevent ordinary selection.",
            "- The empty generated artifact catalog is a separate opt-in artifact interface. Populating it cannot by itself attach these route-bound kernels to the model graph.", ""]
  return "\n".join(lines)


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--json", action="store_true")
  args = parser.parse_args()
  report = inventory()
  print(json.dumps(report, indent=2) if args.json else markdown(report))
  return 0


if __name__ == "__main__": raise SystemExit(main())
