#!/usr/bin/env python3
# adapted from upstream tinygrad sz.py: token-based line counter with a hard budget.
# BOUNDARY: authored vs generated is a FILE PROPERTY, not a path convention. A file is GENERATED iff its head carries
# an `@generated` / `autogenerated` marker (emitted by tinygrad/runtime/autogen). Generated files are DERIVED artifacts:
# reported but never budgeted (they must be reproducible via REGEN=1). Everything else is AUTHORED source.
# BUDGET_DIRS authored lines count against MAX_LINE_COUNT; INFO_DIRS authored lines are reported but unbudgeted.
import os, sys, token, tokenize, itertools, re

BUDGET_DIRS = ["tinygrad", "bench", "structure"]
INFO_DIRS = ["extra"]
EXCLUDE = ["tinygrad/viz/assets"]          # third-party vendored assets (not our authored source, not our @generated)
GEN_MARK = re.compile(r'@generated|autogenerated', re.I)
DEFAULT_MAX_LINE_COUNT = 30000

TOKEN_WHITELIST = [token.OP, token.NAME, token.NUMBER, token.STRING]

def is_docstring(t):
  return t.type == token.STRING and t.string.startswith('"""') and t.line.strip().startswith('"""')

def is_js_token(s): return len(s) and not s.startswith('//')

def is_generated(filepath):
  # a file declares itself generated in its first few lines; the marker is the boundary, not the directory.
  try:
    with open(filepath, errors="ignore") as f: return bool(GEN_MARK.search("".join(itertools.islice(f, 6))))
  except OSError: return False

def gen_stats(base_path="."):
  table = []   # [relpath, lines, tokens_per_line, kind]  kind in {"budgeted","info","generated"}
  for top in BUDGET_DIRS + INFO_DIRS:
    for path, _, files in os.walk(os.path.join(base_path, top)):
      for name in files:
        if not (name.endswith(".py") or name.endswith(".js")): continue
        if any(s in path.replace('\\', '/') for s in EXCLUDE): continue
        filepath = os.path.join(path, name)
        relfilepath = os.path.relpath(filepath, base_path).replace('\\', '/')
        if name.endswith(".js"):
          with open(filepath) as file_: lines = [line.strip() for line in file_.readlines()]
          token_count, line_count = sum(len(line.split()) for line in lines if is_js_token(line)), sum(1 for line in lines if is_js_token(line))
        else:
          try:
            with tokenize.open(filepath) as file_:
              tokens = [t for t in tokenize.generate_tokens(file_.readline) if t.type in TOKEN_WHITELIST and not is_docstring(t)]
          except (tokenize.TokenizeError, SyntaxError) as e:
            print(f"WARNING: failed to tokenize {relfilepath}: {e}", file=sys.stderr); continue
          token_count, line_count = len(tokens), len(set([x for t in tokens for x in range(t.start[0], t.end[0]+1)]))
        if line_count <= 0: continue
        kind = "generated" if is_generated(filepath) else ("budgeted" if top in BUDGET_DIRS else "info")
        table.append([relfilepath, line_count, token_count/line_count, kind])
  return table

if __name__ == "__main__":
  table = gen_stats(sys.argv[1] if len(sys.argv) == 2 else ".")
  if os.getenv("SZ_FILES", "0") == "1":
    for name, lines, tpl, kind in sorted(table, key=lambda x: -x[1]): print(f"{name:80s} {lines:6d} {tpl:6.1f} {kind}")
    print()

  # authored breakdown by top-level dir group (generated excluded from this view)
  authored = [x for x in table if x[3] != "generated"]
  groups = sorted([('/'.join(x[0].rsplit("/", 1)[0].split("/")[0:2]), x[1], x[2]) for x in authored])
  for dir_name, _group in itertools.groupby(groups, key=lambda x: x[0]):
    group = list(_group)
    print(f"{dir_name:30s} : {sum(x[1] for x in group):6d} in {len(group):3d} files")
  print()

  budgeted = sum(x[1] for x in table if x[3] == "budgeted")
  info     = sum(x[1] for x in table if x[3] == "info")
  gen      = sum(x[1] for x in table if x[3] == "generated")
  gen_n    = sum(1 for x in table if x[3] == "generated")
  print(f"   generated (derived, unbudgeted): {gen} in {gen_n} files")
  print(f"       extra (authored, unbudgeted): {info}")
  max_line_count = int(os.getenv("MAX_LINE_COUNT", str(DEFAULT_MAX_LINE_COUNT)))
  print(f"AUTHORED budgeted lines: {budgeted} / {max_line_count}")
  assert max_line_count == -1 or budgeted <= max_line_count, f"OVER BUDGET: {budgeted} > {max_line_count} LINES"
