"""Canonical storage geometry for the GGML K-quant formats used by tinygrad LLM primitives."""

GGML_Q4_K = 12
GGML_Q6_K = 14

QK_BLOCK_ELEMS = 256
Q4_K_BLOCK_ELEMS = QK_BLOCK_ELEMS
Q4_K_BLOCK_BYTES = 144
Q4K_WORDS_PER_BLOCK = Q4_K_BLOCK_BYTES // 4
Q6_K_BLOCK_ELEMS = QK_BLOCK_ELEMS
Q6_K_BLOCK_BYTES = 210
Q6K_HALFWORDS_PER_BLOCK = Q6_K_BLOCK_BYTES // 2
Q8_1_BLOCK_ELEMS = 32
