import pathlib

import pytest

import sz


ROOT = pathlib.Path(__file__).resolve().parents[2]


@pytest.fixture
def boundary_stats(tmp_path):
  files = {
    "tinygrad/authored.py": "first = 1\nsecond = first + 1\n",
    "tinygrad/generated.py": "# @generated by a fixture\nlarge = 1\nstill_large = 2\n",
    "extra/tool.py": "useful = True\n",
    "tinygrad/viz/assets/vendor.js": "vendored code is not ours\n",
  }
  for name, contents in files.items():
    path = tmp_path / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents)

  return {name: (lines, kind) for name, lines, _tokens_per_line, kind in sz.gen_stats(tmp_path)}


def test_generated_files_are_reported_but_not_budgeted(boundary_stats):
  assert boundary_stats["tinygrad/generated.py"] == (2, "generated")
  assert sum(lines for lines, kind in boundary_stats.values() if kind == "generated") == 2


def test_authored_core_files_are_budgeted(boundary_stats):
  assert boundary_stats["tinygrad/authored.py"] == (2, "budgeted")
  assert sum(lines for lines, kind in boundary_stats.values() if kind == "budgeted") == 2


def test_authored_extra_is_reported_separately(boundary_stats):
  assert boundary_stats["extra/tool.py"] == (1, "info")
  assert sum(lines for lines, kind in boundary_stats.values() if kind == "info") == 1


def test_vendored_assets_are_excluded_from_accounting(boundary_stats):
  assert "tinygrad/viz/assets/vendor.js" not in boundary_stats


def test_repository_authored_core_stays_under_ratchet():
  stats = sz.gen_stats(ROOT)
  budgeted = [(name, lines) for name, lines, _tokens_per_line, kind in stats if kind == "budgeted"]
  total = sum(lines for _name, lines in budgeted)
  largest = ", ".join(f"{name}={lines}" for name, lines in sorted(budgeted, key=lambda x: x[1], reverse=True)[:10])
  assert total <= sz.DEFAULT_MAX_LINE_COUNT, \
    f"authored-core LOC ratchet exceeded: {total} > {sz.DEFAULT_MAX_LINE_COUNT} ({total-sz.DEFAULT_MAX_LINE_COUNT} over); largest files: {largest}"


def test_vendored_exclusion_stays_narrow():
  assert sz.EXCLUDE == ["tinygrad/viz/assets"]


def test_runtime_autogen_modules_declare_generated_marker():
  missing = []
  for path in (ROOT / "tinygrad/runtime/autogen").rglob("*.py"):
    if path.name == "__init__.py": continue
    if not sz.is_generated(path): missing.append(str(path.relative_to(ROOT)))
  assert missing == []


def test_runtime_autogen_init_files_are_authored():
  for path in (ROOT / "tinygrad/runtime/autogen").rglob("__init__.py"):
    assert not sz.is_generated(path), str(path.relative_to(ROOT))
