#!/usr/bin/env python3
"""Durable-artifact portability guard (audit P2/P3).

The override rule "no absolute checkout paths in artifact contents; no machine-float serialization in golden-locked
artifacts" is enforced here for the DURABLE / live surface -- the ledgers + current generated artifacts that are
read or regenerated by live code. It is deliberately NOT applied to the ~82 frozen historical bench artifacts: many
are golden-locked by reproduce tests (test_llm_training_data_probe / test_qk_experiment_matrix / test_qk_ansor_transition
/ test_qk_search_spec / test_llm_rollout*) and some absolute paths are FUNCTIONAL inputs (e.g. `source_artifacts`),
so rewriting them would break those tests and lose recorded data for a cosmetic gain (see
docs/repo-principles-audit-20260621.md P2/P3). New work must keep the durable surface clean; this guard fails if it
regresses. No GPU / no tinygrad import.

Run: PYTHONPATH=. python -m unittest test.unit.test_artifact_portability -v
"""
from __future__ import annotations
import pathlib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
CHECKOUT = "/home/ubuntu/tinygrad-arkey"  # the repo checkout prefix that must never be baked into a durable artifact

# Durable / live tracked artifacts (ledgers + current generated maps) -- the surface live code reads/regenerates.
DURABLE = [
  "bench/qk-decode-eval/candidates.json", "bench/qk-decode-eval/schema.json",
  "bench/qk-decode-eval/binding_templates.json", "bench/qk-lifecycle-search/search_policy.json",
  "bench/qk-lifecycle-search/evaluator_contract.json", "bench/qk-lifecycle-search/refutations.json",
  "bench/qk-active-surface-reduction/inventory.json", "bench/qk-active-surface-reduction/v2_keep_seed.json",
  "bench/qk-active-surface-reduction/docs_index.json",
]


class TestArtifactPortability(unittest.TestCase):
  def test_durable_artifacts_have_no_absolute_checkout_path(self):
    offenders = []
    for rel in DURABLE:
      p = ROOT / rel
      if p.exists() and CHECKOUT in p.read_text(errors="ignore"):
        offenders.append(rel)
    self.assertEqual(offenders, [], f"durable artifacts bake the absolute checkout path {CHECKOUT!r}: {offenders}")

  def test_durable_list_exists(self):
    # at least the core ledgers must be present (guards against a renamed/moved authority going unchecked)
    for rel in ("bench/qk-decode-eval/candidates.json", "bench/qk-lifecycle-search/search_policy.json"):
      self.assertTrue((ROOT / rel).exists(), f"durable ledger missing: {rel}")


if __name__ == "__main__":
  unittest.main()
