#!/usr/bin/env python3
"""PMS-R5: G3 Q4_K GEMV LaneMap TEMPLATE audit (provenance + generalization, NOT speed).

Answers, for the promoted default decode Q4_K GEMV (extra/qk/gemv_g3_codegen_lowering.py
q4k_g3_lanemap_gemv_kernel, lowered from extra/qk/gemv_g2_lanemap.py Q4KGateUpLaneMap):

  1. which pieces are parameterized by shape/quant/role vs hardcoded for Q4_K/Qwen3/gfx1100;
  2. what is generated by the G3 codegen vs hand-authored topology;
  3. the minimal generic LaneMapTemplate schema (lane ownership, packed-word load, dequant body, reduction,
     output store, shape guards);

and PROVES the template is lossless: it RECONSTRUCTS each eligible G3 route FROM the template parameters and shows
the emitted UOp program is byte-identical (UOp .key) to the current default emission, plus that the template's declared
packed-word-index formula matches the LaneMap reference for a coordinate sample. Speed-equivalence is CITED from the
existing promotion artifact (bench/amd-isa-backend-g3-weight-promotion), NOT re-measured.

No GPU: UOp construction is symbolic. Run:  PYTHONPATH=. python3 extra/qk/lanemap_template_audit.py
"""
from __future__ import annotations
import json, pathlib
from dataclasses import dataclass, field, asdict

from tinygrad.uop.ops import UOp
from tinygrad.dtype import dtypes
from extra.qk.amd_warp_reduce import WARP
from extra.qk.gemv_g3_codegen_lowering import q4k_g3_lanemap_gemv_kernel
from extra.qk.gemv_g2_lanemap import Q4KGateUpLaneMap

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "bench/qk-lanemap-template-audit"
SPEED_ARTIFACT = "bench/amd-isa-backend-g3-weight-promotion/latest.json"

# The three eligible Q4_K decode roles G3 is promoted for (rows = out_features = N, k = in_features = K).
ELIGIBLE_ROLES = {
  "ffn_gate_up": {"rows": 12288, "k": 4096},
  "ffn_down":    {"rows": 4096,  "k": 12288},
  "attn_qo":     {"rows": 4096,  "k": 4096},
}

# ---- the minimal generic LaneMapTemplate schema (what a search-owned lane-map family must declare) ----
LANEMAP_TEMPLATE_SCHEMA = {
  "_doc": "minimal generic LaneMapTemplate: the degrees of freedom that fully describe a packed-quant GEMV lane-map "
          "route. The promoted G3 Q4_K route is one instantiation; nothing in its emission is hand-authored outside "
          "these fields.",
  "parameterized_by_shape_quant_role": {
    "rows": "= out_features (N); per-role (gate_up 12288, down 4096, qo 4096)",
    "k": "= in_features (K); per-role (gate_up 4096, down 12288, qo 4096)",
    "lane_extent": "wave width; gfx1100 wave32 (WARP). Parameterized but currently fixed to the GPU wave.",
  },
  "hardcoded_for_q4k_qwen3_gfx1100": {
    "qk_k": "256 (Q4_K super-block element count)",
    "q4k_words_per_block": "36 uint32 words per Q4_K block (quant layout)",
    "q4k_quant_word_base": "4 (scale/min words precede the 32 quant words)",
    "words_per_group": "8 (Q4_K gate/up lane map requires 8 packed words per group)",
    "block_groups": "4 (lane_extent == block_groups * words_per_group == 32)",
    "dequant_body": "extra.qk.quant.q4_k_gemv_primitive._q4k_block_dot_packed_load (Q4_K packed dequant+dot)",
    "wave": "wave32 (gfx1100 / QK_AMD_GFX1100_ARCH_OK)",
  },
  "template_pieces": {
    "lane_ownership": "lane = block_group * words_per_group + word_col  (Q4KGateUpLaneMap.lane_expr); "
                      "LanePartition(lane, lane_extent, words_per_group)",
    "packed_word_load": "(row*k_blocks + (block_group*blocks_per_group + local_block))*q4k_words_per_block "
                        "+ q4k_quant_word_base + group_pair*words_per_group + word_col "
                        "(Q4KGateUpLaneMap.packed_word_index_expr / packed_word_index_ref)",
    "dequant_body": "_q4k_block_dot_packed_load(words, x, base, blk, word_col) per reduce block",
    "reduction": "lane_partition_reduce_sum(acc, LanePartition)  (cross-lane sum over the partition)",
    "output_store": "out[row].store(total)  (one fp32 per output row)",
    "shape_guards": ["k % qk_k == 0", "k_blocks % block_groups == 0",
                     "lane_extent == block_groups * words_per_group", "words_per_group == 8",
                     "q4k_words_per_block == 36"],
  },
  "generated_vs_hand_authored": {
    "generated": "the entire wave32 UOp program (special/range axes, packed-word index UOps, reduce loop, cross-lane "
                 "reduce, output store, KernelInfo name) is emitted by q4k_g3_lanemap_gemv_kernel from the LaneMap; "
                 "no per-shape kernel is hand-written.",
    "hand_authored_topology": "the Q4_K packed-word LAYOUT constants (36 words, base 4, 8 words/group, 4 groups) and "
                              "the _q4k_block_dot_packed_load dequant micro-op are the quant-format primitives the "
                              "template binds to; the lane partition + reduce are reusable library pieces.",
  },
}


@dataclass(frozen=True)
class LaneMapTemplate:
  """One instantiation of the generic lane-map family. The G3 default IS this template at the 3 eligible shapes."""
  role: str
  rows: int
  k: int
  lane_extent: int = WARP
  quant: str = "Q4_K"
  family: str = "lanemap"
  target: str = "AMD_gfx1100"
  shape_guards: tuple = field(default=())

  def lanemap(self) -> Q4KGateUpLaneMap:
    return Q4KGateUpLaneMap(k=self.k, n=self.rows, lane_extent=self.lane_extent)

  def emit_sink(self) -> UOp:
    """Reconstruct the kernel FROM the template params -> the named wave32 UOp sink."""
    return q4k_g3_lanemap_gemv_kernel(self.rows, self.k, self.lane_extent)(*_placeholders(self.rows, self.k))


def _placeholders(rows: int, k: int):
  return (UOp.placeholder((rows,), dtypes.float32, 0),
          UOp.placeholder((1,), dtypes.uint32, 1),
          UOp.placeholder((rows,), dtypes.float32, 2))


def _reference_sink(rows: int, k: int) -> UOp:
  """The exact emission the default route uses (tinygrad/llm/model.py:264 fxn=q4k_g3_lanemap_gemv_kernel(N,K))."""
  return q4k_g3_lanemap_gemv_kernel(rows, k)(*_placeholders(rows, k))


def _packed_index_matches(lm: Q4KGateUpLaneMap) -> bool:
  """The template's declared packed-word index formula must match the LaneMap reference at a coordinate sample."""
  import itertools
  for row, bg, lb, gp, wc in itertools.product(
      (0, 1, lm.n - 1), range(lm.block_groups), (0, lm.blocks_per_group - 1), range(lm.group_pairs), (0, lm.words_per_group - 1)):
    if lb >= lm.blocks_per_group: continue
    ref = lm.packed_word_index_ref(row, bg, lb, gp, wc)
    blk = bg * lm.blocks_per_group + lb
    exp = (row * lm.k_blocks + blk) * lm.q4k_words_per_block + lm.q4k_quant_word_base + gp * lm.words_per_group + wc
    if ref != exp: return False
  return True


def reconstruct_role(role: str, rows: int, k: int) -> dict:
  t = LaneMapTemplate(role=role, rows=rows, k=k,
                      shape_guards=tuple(LANEMAP_TEMPLATE_SCHEMA["template_pieces"]["shape_guards"]))
  lm = t.lanemap(); lm.validate()
  tmpl_sink = t.emit_sink()
  ref_sink = _reference_sink(rows, k)
  key_match = (tmpl_sink.key == ref_sink.key)
  name_match = (tmpl_sink.arg.name == ref_sink.arg.name == f"q4k_g3_lanemap_gemv_{rows}_{k}")
  return {"role": role, "rows": rows, "k": k, "kernel_name": tmpl_sink.arg.name,
          "uop_key_identical_to_default": bool(key_match), "kernel_name_match": bool(name_match),
          "packed_word_index_matches_reference": _packed_index_matches(lm),
          "lanemap_serialized": lm.serialize()}


def main() -> int:
  OUT.mkdir(parents=True, exist_ok=True)
  recon = {role: reconstruct_role(role, **shp) for role, shp in ELIGIBLE_ROLES.items()}
  lossless = all(r["uop_key_identical_to_default"] and r["kernel_name_match"]
                 and r["packed_word_index_matches_reference"] for r in recon.values())
  speed = "MISSING"
  sp = ROOT / SPEED_ARTIFACT
  if sp.exists():
    d = json.load(open(sp))
    speed = d.get("verdict", "MISSING")
  result = {
    "scope": "PMS-R5 G3 LaneMap template audit (provenance + lossless reconstruction; speed CITED not re-measured)",
    "verdict": "PMS_R5_PASS_G3_TEMPLATE_PROVEN" if lossless else "PMS_R5_BLOCKED_TEMPLATE_NOT_LOSSLESS",
    "lossless_reconstruction": lossless,
    "proof_method": "static UOp .key equivalence of template-emitted vs default-route kernel + packed-word-index "
                    "formula match; no GPU, no re-measurement.",
    "writer": "extra/qk/gemv_g3_codegen_lowering.py q4k_g3_lanemap_gemv_kernel (lowered from extra/qk/gemv_g2_lanemap.py)",
    "default_route_attribution": "tinygrad/llm/model.py:255-264 (BUBBLEBEAM_FUTURESIGHT default-on, g3_bubblebeam_shape)",
    "lanemap_template_schema": LANEMAP_TEMPLATE_SCHEMA,
    "reconstruction_per_role": recon,
    "speed_equivalence": {"source": SPEED_ARTIFACT, "cited_verdict": speed,
                          "note": "speed-equivalent to owned warp (-0.13..+0.41% ctx512-4096), token-identical; "
                                  "NOT re-measured here (R5 is provenance, not speed)."},
    "do_not": ["do not chase speed", "do not rewrite the promoted G3 route (route identity/correctness must stay exact)"],
  }
  json.dump(result, open(OUT / "latest.json", "w"), indent=2)
  md = ["# PMS-R5 G3 LaneMap Template Audit", "",
        f"Verdict: **{result['verdict']}**  (lossless reconstruction = {lossless})", "",
        f"Speed-equivalence (cited, not re-measured): `{speed}` from `{SPEED_ARTIFACT}`.", "",
        "| role | rows(N) | k(K) | kernel | UOp key == default | name match | packed-idx match |",
        "|---|---:|---:|---|:--:|:--:|:--:|"]
  for role, r in recon.items():
    md.append(f"| {role} | {r['rows']} | {r['k']} | `{r['kernel_name']}` | {r['uop_key_identical_to_default']} | "
              f"{r['kernel_name_match']} | {r['packed_word_index_matches_reference']} |")
  md += ["", "Template is lossless: emitting each eligible role FROM the LaneMapTemplate params yields a UOp program "
         "byte-identical (UOp .key) to the current default G3 emission, and the declared packed-word-index formula "
         "matches the LaneMap reference. Provenance + parameterization in `lanemap_template_schema`.", ""]
  (OUT / "summary.md").write_text("\n".join(md))
  print(result["verdict"], "| lossless:", lossless, "| speed cited:", speed)
  for role, r in recon.items():
    print(f"  {role}: key_match={r['uop_key_identical_to_default']} name_match={r['kernel_name_match']} "
          f"idx_match={r['packed_word_index_matches_reference']}")
  return 0 if lossless else 1


if __name__ == "__main__":
  raise SystemExit(main())
